// exports.serverResponseMessage = {
module.exports = {

  user: {
    school_not_exist: 'This school does not exists',
    school_email_exist: 'This school email already exists',
    school_mobile_exist: 'This school mobile number already exists',
    schooladmin_email_exist: 'This school admin email already exists',
    schooladmin_mobile_exist: 'This school admin mobile number already exists',
    school_create_success: "School created successfully",
    school_create_error: "School not create",
    school_update_success: "School updated successfully",
    school_update_error: "School not update",
    school_get_success: "School data retrive successfully",
    admin_login_success: 'Admin login successfully',
    admin_not_exist: 'Admin does not exists',
    school_delete_success: "School deleted successfully",
    school_delete_error: "School not delete",
    school_in_current_trip: "School school is in current trip",

    surveyor_mobile_exist: 'This surveyor mobile number already exists',
    school_already_assign_surveyor: "This school already assign to another surveyor",
    surveyor_create_success: "Surveyor created successfully",
    surveyor_update_success: "Surveyor updated successfully",
    surveyor_update_error: "Surveyor not update",
    surveyor_get_success: "Surveyor data retrive successfully",
    surveyor_not_exist: "This surveyor does not exists",
    surveyor_delete_success: "Surveyor deleted successfully",
    surveyor_delete_error: "Surveyor not delete",
    surveyor_in_current_trip: "This surveyor is in current trip",

    driver_mobile_exist: 'This driver mobile number already exists',
    driver_create_success: "Driver created successfully",
    driver_update_success: "Driver updated successfully",
    driver_update_error: "Driver not update",
    driver_get_success: "Driver data retrive successfully",
    driver_not_exist: "This driver does not exists",
    driver_delete_success: "Driver deleted successfully",
    driver_delete_error: "Driver not delete",
    driver_in_current_trip: "This driver is in current trip",

    student_mobile_exist: 'This student mobile number already exists',
    student_create_success: "Student created successfully",
    student_update_success: "Student updated successfully",
    student_update_error: "Student not update",
    student_get_success: "Student data retrive successfully",
    student_not_exist: "This student does not exists",
    student_delete_success: "Student deleted successfully",
    student_delete_error: "Student not delete",
    student_in_current_trip: "This student is in current trip",

    token_success:"Device Token updated successfully",
    otp_send_success: 'OTP is sent to Your Mobile Number',
    otp_resend_success: 'OTP is sent to Your Mobile Number',
    mobile_number: 'Mobile number should be 10 digit only',

    user_not_exist: 'User not exist',
    incorrect_otp: 'OTP does not match',
    login_success: 'Login successfully',
    register_success: 'Register successfully, Please check your otp',
    wrong_email_password: 'Incorrect email or password',

    import_extension: "Only CSV file allowed",
    import_success: "Student import successfully",
    import_error: "Student not import",
    email_exist: 'Email already exist',
    mobile_exist: 'Mobile already exist',
    data_create_success: "Data create successfully",
    data_create_error: "Data not create",
    data_update_success: "Data update successfully",
    data_update_error: "Data not update",
    data_get_success: "Data retrive successfully",
    data_get_error: "Data not retrive",
    data_delete_success: "Data delete successfully",
    data_delete_error: "Data not delete",
    file_upload__success: "File upload successfully",
    data_in_current_trip: "This data is in current trip, please complete your trip first",
  },
  bus: {
    data_create_success: "Bus created successfully",
    data_create_error: "Bus not create",
    data_update_success: "Bus updated successfully",
    data_update_error: "Bus not update",
    data_get_success: "Bus date retrive successfully",
    data_get_error: "Bus not retrive",
    data_delete_success: "Bus deleted successfully",
    data_delete_error: "Bus not delete",
    data_not_exist: "This bus is not exist",
    driver_already_assigned: "This driver already assigned to another bus",
    driver_assigned_error: "Driver not assigned in another bus",
    assigned_error: "please assign bus and driver before published route",
    unique_bus_number: "This bus number is already exist",
    data_in_current_trip: "This bus is in current trip",
  },
  route: {
    data_create_success: "Route created successfully",
    data_create_error: "Route not create",
    data_update_success: "Route updated successfully",
    data_update_error: "Route not update",
    data_get_success: "Route data retrive successfully",
    data_get_error: "Route not retrive",
    data_delete_success: "Route deleted successfully",
    data_delete_error: "Route not delete",
    data_not_exist: "This route does not exists",
    stop_not_exist: "Route and Stop not exist",
    surveyor_already_assign: "Surveyor already assign in another route",
    import_success: "Route import successfully",
    import_error: "Route not import",
    data_in_current_trip: "This route is in current trip",
  },
  help: {
    data_create_success: "Help create successfully",
    data_create_error: "Help not create",
    data_update_success: "Help update successfully",
    data_update_error: "Help not update",
    data_get_success: "Help retrive successfully",
    data_get_error: "Help not retrive",
    data_delete_success: "Help delete successfully",
    data_delete_error: "Help not delete",
    data_not_exist: "Help not exist",
    data_needed: "Help title and description needed",
  },
  trip: {
     data_create_success: "Trip create successfully",
    data_create_error: "Trip not create",
    data_not_exist: "This trip is not exist",
    data_complete_success: "Trip completed successfully",
    data_complete_error: "Trip not complete",
    data_update_success: "Trip update successfully",
    data_update_error: "Trip not update",
    data_get_success: "Trip data retrive successfully",
    data_get_error: "Trip not retrive",
    data_delete_success: "Trip delete successfully",
    data_delete_error: "Trip not delete",
    data_needed: "Trip title and description needed",
    location_get_for_trip: "Bus current location get successfully",
    sos_success: "SOS sent successfully",
    sos_error: "SOS not sent",
    location_success: "Driver current location retrive successfully",
  },
  noticeBoard: {
    NOTICE_CREATED: 'notice Created Succesfully',
    NOTICE_UPDATE: 'notice Updated Succesfully',
    NOTICE_DELETE: 'notice Deleted Succesfully',
    NOTICE_READ: 'notice Fatched Succesfully',
    NOTICE_READ_ERROR: 'notice not Fatched',
    FAILURE_NOTICE_CREATE: 'Unable to Create notice',
    FAILURE_NOTICE_UPDATE: 'Unable to Update notice',
    FAILURE_NOTICE_DELETE: 'Unable to Delete notice',
    FAILURE_NOTICE_READ: 'Unable to Get notice',
    NOTICE_EXISTS: 'notice Already Exists',
    NOTICE_DOES_NOT_EXISTS: 'This notice does Not exists',
  },
  feedback: {
    data_create_success: "Feedback created successfully",
    data_create_error: "Feedback not create",
    data_update_success: "Feedback updated successfully",
    data_update_error: "Feedback not update",
    data_get_success: "Feedback data retrive successfully",
    data_get_error: "Feedback not retrive",
    data_delete_success: "Feedback deleted successfully",
    data_delete_error: "Feedback not delete",
    data_not_exist: "This feedback does not exists",
    data_needed: "Please fill title and description",
    data_approved_success: "Request approved successfully",
    data_reject_success: "Request reject successfully",
  },

  Catch_Error: 'Something went wrong',
};
